# Credit card approval
In this notebook something happens $\sin x = \frac{1}{x^2}$

In [50]:
import pandas as pd
# Reading the data file 
cc_apps = pd.read_csv('crx.data', header=None)
# Inspecting the content
cc_apps.head()

  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

## Inspecting the file

In [51]:
#summary statistics
cc_apps_stats=cc_apps.describe()
print(cc_apps_stats)
print('\n')

#DataFrame Information
cc_apps_info = cc_apps.info()
print(cc_apps_info)

#Inspecting missing files at the end of the file
cc_apps.tail(20)

               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
0     690 non-null object
1     690 non-null object
2     690 non-null float64
3     690 non-null object
4     690 non-null object
5     690 non-null object
6     690 non-null object
7     690 non-null float64
8     690 non-null object
9     690 non-null object
10    690 non-null int64
11    690 non-null object
12    690 non-null object
13    690 non-null object
14    690 non-null int64
15    690 non-null object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.3+ KB
None

    0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670  b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671  b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672  a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

## Cleaning the file

In [52]:
import numpy as np
#replacing the '?' with NaN through np.nan
cc_apps = cc_apps.replace('?', np.nan)

#cheking again the tail of the DataFrama to check the replaced values
cc_apps.tail(20)

      0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670    b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671    b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672    a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  NaN  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674    a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675    a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676    a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677    b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678    a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679    a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680    b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681    b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682    b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683    b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684    b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685    b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686    a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687    a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688    b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689    b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

## Filing the NaN values with their respective mean values

In [53]:
#replacing missing values with the correspondent mean value
cc_apps.fillna(cc_apps.mean(), inplace=True)

#counting the NaN missing values to verify the replacement
cc_apps.isnull().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

There is still some missing values at columns 0, 1, 3, 4,...

In [54]:
#iterating over each column in the DF cc_apps
for col in cc_apps:
    #checking if the column type is object 
    if cc_apps[col].dtypes == 'object':
        #input the most frequent value
        cc_apps = cc_apps.fillna(cc_apps[col].value_counts().index[0])
        
#checking again for missing values
cc_apps.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

## Preprocessing the data $i$
Transform all the column dtypes to numeric

In [55]:
#Import LabelEncoder
from sklearn.preprocessing import LabelEncoder
#Initiate the Encoder
le = LabelEncoder()
#iterating over each column in the DataFrame
for col in cc_apps:
    #checking the type of each column
    if cc_apps[col].dtypes == 'object':
        #making the transformation
        cc_apps[col] = le.fit_transform(cc_apps[col])

## Spliting into test and training set (for Machine Learning application)

In [56]:
#importing train_test_split library
from sklearn.model_selection import train_test_split

#droping 11 and 13 features and converting the DF to NP array
cc_apps= cc_apps.drop([11, 13], axis=1)
cc_apps = cc_apps.values

#spliting features and labels (predictors and target variable)
X,y = cc_apps[:,0:13], cc_apps[:,13]

#making the test and training sets (30% of the data to test set with a seed of 42)

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=42)

## Preprocessing the data $ii$
Scaling the data between 0 and 1

In [57]:
#importing MinMaxScaler for Scaling the data
from sklearn.preprocessing import MinMaxScaler

#Initiate the Scaler object
scaler = MinMaxScaler(feature_range=(0,1))
#Scaling the predictors test and train set
rescaledX_train = scaler.fit_transform(X_train)
rescaledX_test = scaler.fit_transform(X_test)

## Using Logistic Regression into the train set

In [63]:
#Importing the Logistic Regression model
from sklearn.linear_model import LogisticRegression

#Initiate the logistic Regression object
logreg = LogisticRegression(solver='liblinear')

#Fitting the test data
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

## Making predictions and evaluating performance

In [64]:
#importing confusion_matrix
from sklearn.metrics import confusion_matrix

#making predictions from the test set
y_pred =logreg.predict(rescaledX_test)

#printing the score of the model
print('Logistic Regression accuracy: ', logreg.score(rescaledX_test, y_test))

#printing the confusion matrix
print(confusion_matrix(y_test, y_pred))

Logistic Regression accuracy:  0.8405797101449275
[[89  8]
 [25 85]]

## Optimizing the model through parameter Grid Search

In [65]:
#importing GridSearchCV
from sklearn.model_selection import GridSearchCV
#defining the grid values
tol = [0.01,0.001,0.0001]
max_iter = [100, 150, 200]

#Creating the grid
param_grid = dict(tol=tol, max_iter=max_iter)

## Finding the best model

In [66]:
#Initiate the grid search the defined parameters
grid_model = GridSearchCV(estimator=logreg, param_grid=param_grid, cv=5)

#Rescaling X
rescaledX = scaler.fit_transform(X)

#Fit the data to the grid_model
grid_model_result= grid_model.fit(rescaledX, y)

#Printing the results 
best_score, best_params= grid_model_result.best_score_, grid_model_result.best_params_
print("Best: %f using %s" % (best_score, best_params))

Best: 0.853623 using {'max_iter': 100, 'tol': 0.01}